theme: jekyll-theme-cayman
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Cubo de leds 4x4x4
description: Proyecto final del Equipo 10 del curso "Integración de Sistemas y Arquitecturas" - BUAP - Otoño 2021
show_downloads: true
